In [4]:
import numpy as np


In [7]:
data = [1,2,3,4,5]
np_array = np.array(data)
print(np_array.shape)

np_array2 = np_array.astype(np.float64)
print(np_array2.dtype)

(5,)
float64


In [9]:
np_array3 = np.linspace(0, 1, 10)
print(np_array3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [16]:
np_array5 = np.array([1,2,3,4,5])
print(np_array5.mean())

# for num in np_array5:
#     print(num < 2)
print(np_array5[np_array5 < 2])

3.0
[1]


In [13]:
np_array_first = np.array([1,2,3])
np_array_second = np.array([4,5,6])
np_array_second = np.concatenate((np_array_first, np_array_second))
print(np_array_second)

[1 2 3 4 5 6]


In [14]:
np.array_split(np_array_second,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [30]:
matrix = np.array([(1,2,3),(4,5,6)], dtype=np.float64)
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)

(2, 3)
2
6


In [31]:
matrix.reshape(1,6)


array([[1., 2., 3., 4., 5., 6.]])

In [28]:
matrix.resize(2,2)
print(matrix)

[[1. 2.]
 [3. 4.]]


In [33]:
matrix2 = np.arange(16).reshape(2,8)
print(matrix2)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
#массив нулей
np.zeros((2,3))
#массив единиц
np.ones((2,3))
#матрица с единицами на диагонале
np.eye(5)
#матрица заданного размера одинаковых значений
np.full((3,3),9)

In [34]:
matrix.dot(matrix2) # скалярное произведение

ValueError: shapes (2,3) and (2,8) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
matrix_axis = np.random.random((3,3))
matrix_axis

array([[0.77336454, 0.50547009, 0.86172991],
       [0.82358163, 0.40770404, 0.74650429],
       [0.64669168, 0.94320143, 0.21083101]])

In [57]:
matrix_axis.max(axis=0)

array([0.82358163, 0.94320143, 0.86172991])

In [45]:
np.delete(matrix_axis,1,axis=0) #axis=0- строки, axis=1- столбцы

array([[0.00495475, 0.83503308, 0.28944929],
       [0.07907969, 0.21552178, 0.32938402]])

In [52]:
matrix_simp = np.arange(9).reshape(3,3)
matrix_simp.max(axis=0) # найдет макс значение из каждого столбца

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (908687531.py, line 2)

In [85]:
matrix_alg = np.arange(16)
matrix_alg.resize(4,4)
matrix_alg[0,0] = 10
matrix_alg
#matrix_alg.T # траспонирование

#matrix_alg.flatten() # в массив

#np.linalg.inv(matrix_alg) # обратная

#np.trace(matrix_alg) # след


array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
np.info(np.zeros) # справочник

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------